format = """
[┌───────────────────> ](bold blue)$git_branch$git_state$git_metrics$git_status$cmake$python$lua
[│](bold blue)$cmd_duration$directory
[└───>](bold blue) $character"""

[character]
success_symbol = "[❯](bold blue) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[❮](bold green)"

[directory]
truncate_to_repo = false
read_only = " "
truncation_length = 8
truncation_symbol = "…/"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
truncation_length = 4
truncation_symbol = ".."

[git_status]
style = "yellow"

[lua]
symbol = ""

[python]
symbol = " "
